language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run build:storybook
  - npm run build:en
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist/storybook
  on:
    branch: master
