on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
name: Build INT 🛠️

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 'v16.13.2'
    - run: yarn
    - run: yarn build:int