on: [pull_request]
name: Code formatting and testing languages✍️


steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
  with:
    node-version: 'v16.13.2'
- run: yarn
- run: yarn format
- run: yarn build:i18n:generate-testing
- uses: EndBug/add-and-commit@v4
  env:
    GITHUB_TOKEN: ${{ secrets.ORCID_MACHINE }}