name: Build and Deploy

on:
  push:
    branches:
      - "storybook-2023"
    # paths: ["src/stories/**", ".storybook/**"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'v16.x'
          cache: 'yarn'
      - run: yarn
      - run: yarn build:${{ inputs.artifact_name }}
      - name: Install and Build
        run: | # Install npm packages and build the Storybook files
          yarn install
          yarn run build:storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: dist/storybook/ng-orcid # The folder that the build-storybook script generates files.